### ISSUE TITLE
Criar ansible role

### ISSUE THREAD

**Issue by gomex** [mentoriaiac/iac_role_node_rke#1]
DoD:

 - [ ] Atende essa lista de requerimentos: https://rancher.com/docs/rke/latest/en/os/
 - [ ] Ubuntu 20.04 (LTS)
 - [ ] Ter algum teste (molecule)

Usaremos o docker por hora, não daremos opção pra trocar o runtime container.

**Comment by hazkall** [comment]
@gomex 

Durante o desenvolvimento da role surgiu a duvida de trabalhar com as versões do Docker e Kubectl com Major ou Minor, então na primeira versão da PR pegamos a ultima versão do docker e kubernetes e setamos na variavel do ansible, habiitando a possibilidade de costumização se houver necessidade.

**Comment by gomex** [comment]
O PR #2 resolve boa parte dos requisitos pra fechar essa issue aqui, mas ainda falta.

Uma coisa que consigo ver rapidamente aqui é: Remover o swap. Outras coisas podem aparecer, e não tem problema. Vou fazer o merge do PR e dai podemos criar outro pra atender essas demandas, ok?

**Comment by gomex** [comment]
Essa issue foi resolvida.
